# Generated by Django 5.1.15 on 2026-03-25 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                (
                    "slug",
                    models.SlugField(blank=True, unique=True, verbose_name="URL标识"),
                ),
                ("content", models.TextField(verbose_name="内容 (Markdown)")),
                (
                    "content_html",
                    models.TextField(blank=True, verbose_name="渲染后HTML"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "草稿"), ("published", "已发布")],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发布时间"
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, upload_to="covers/", verbose_name="封面图"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="blog.category",
                        verbose_name="分类",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="posts",
                        to="blog.tag",
                        verbose_name="标签",
                    ),
                ),
            ],
            options={
                "verbose_name": "博文",
                "verbose_name_plural": "博文",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
