# Generated by Django 5.1.15 on 2026-03-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="FriendLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                ("url", models.URLField(verbose_name="链接地址")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                ("avatar", models.URLField(blank=True, verbose_name="头像URL")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否显示"),
                ),
            ],
            options={
                "verbose_name": "友链",
                "verbose_name_plural": "友链",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Moment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="内容 (Markdown)")),
                (
                    "content_html",
                    models.TextField(blank=True, verbose_name="渲染后HTML"),
                ),
                (
                    "images",
                    models.JSONField(blank=True, default=list, verbose_name="图片列表"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "说说",
                "verbose_name_plural": "说说",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=50, unique=True, verbose_name="配置键"),
                ),
                ("value", models.TextField(verbose_name="配置值")),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="说明"),
                ),
            ],
            options={
                "verbose_name": "站点配置",
                "verbose_name_plural": "站点配置",
            },
        ),
    ]
